name: test

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: main tests
        run: ./tests/run.sh

      - name: sudo tests
        run: sudo ./tests/sudo.sh

      - name: lint
        run: ./scripts/lint.sh
